### ISSUE TITLE
Difficulty in dynacally assigning a faculty to a department

### ISSUE THREAD

**Issue by Timbaron** [humaneguy/studently-api#2]
I am trying to assign a faculty to a particular department through seeder. But i keep getting an error,

![image](https://user-images.githubusercontent.com/36372628/113945296-fa7dca80-97fd-11eb-8f7a-6bcb133998d3.png)

What i did:
                $departments = ['Biological Science','Chemical Science','Earth Science','Mathematical Science','Physics'];

        $faculties = Faculty::pluck('id')->toArray();
        foreach($departments as $department)
        {
            Department::create(['name' => $department,'faculty_id' => array_rand($faculties));
        }

After getting the list of all the faculties Id, it returned an associative array, How do i loop through this type of array in this situation?

And any ideas on how i can assign a specific department to a specific faculty?.

Thanks

**Comment by otilor** [comment]
It's because of your foreign key constraints. Check the PR you opened. I mentioned that.
